package:
  name: "chromodoter"
  version: "0.3"
about:
  summary: "Chromodoter - tool to draw dotplots "
source:
  path: ../
requirements:
  build:
    - python {{ python }}
    - pip
    - setuptools
    - numpy
    - pandas
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - matplotlib

build:
  script: python setup.py install